name: digitalocean-app-platform-django
region: ams
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: jonwhittlestone/digitalocean-app-platform-django
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: digitalocean-app-platform-django
  routes:
  - path: /
  run_command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8080 --worker-tmp-dir /dev/shm --chdir api